EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Political Leaders Emerging', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Political';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Boston leaders say all the right things', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Political';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Loudest Neighborhoods get non-motorized infrastructure', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Political';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Boston is thinking long-term; more on the table', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Political';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Goals more accepted by the public leadership', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Political';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Increased inner city wealth driving better transit', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Economic';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Increased MBTA ridership', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Economic';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Climate change mitigation', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Economic';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Businesses benefit from complete streets', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Economic';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Membership area populations growing', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Economic';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Increased support for sustainable transportation', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Social';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Increased focus on equity in transportation', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Social';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Culture growing around biking and transportation', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Social';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Neighborhood Leaders Emerging', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Social';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Individual Leaders Emerging', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Social';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Demographic opportunities in churches, large universities, neighborhood groups, elderly folks', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Social';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Unique activist network centralized support', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Social';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Role as consensus-builder', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Social';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Accept all projects our constituents request', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Social';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Demographic shifts (equity atlas)', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Social';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Demand-based parking pricing', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Technological';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Private services using old rail lines', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Technological';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Congestion tolls', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Technological';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'All-door boarding of buses and light-rail trains', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Technological';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Automated walk signals', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Technological';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Protected bike lines', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Technological';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Traffic signal timing', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Technological';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Increased mapping data being utilized', @strategy_type_name = 'Opportunity', @strategy_category_name = 'Technological';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Divide between Boston leaders talk and actions', @strategy_type_name = 'Threat', @strategy_category_name = 'Political';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Streets not yet considered public spaces', @strategy_type_name = 'Threat', @strategy_category_name = 'Political';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Political election process puts streets on the backburner', @strategy_type_name = 'Threat', @strategy_category_name = 'Political';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Fiscal Tightness', @strategy_type_name = 'Threat', @strategy_category_name = 'Political';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Transit will not get the funding it needs', @strategy_type_name = 'Threat', @strategy_category_name = 'Political';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Lack of activity in Mattapan and Dorchester, 128 corridor', @strategy_type_name = 'Threat', @strategy_category_name = 'Political';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Increased Cost of Housing', @strategy_type_name = 'Threat', @strategy_category_name = 'Economic';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Urban displacement', @strategy_type_name = 'Threat', @strategy_category_name = 'Economic';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Relationship between access to transportation and jobs', @strategy_type_name = 'Threat', @strategy_category_name = 'Economic';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Same routes as 50 years ago for bus systems', @strategy_type_name = 'Threat', @strategy_category_name = 'Economic';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Not enough fiscal oversight, control, and visibility', @strategy_type_name = 'Threat', @strategy_category_name = 'Economic';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Image problem for transportation agencies', @strategy_type_name = 'Threat', @strategy_category_name = 'Economic';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Lack of housing to places near train stations', @strategy_type_name = 'Threat', @strategy_category_name = 'Economic';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Polarization of rich and poor, related to geography', @strategy_type_name = 'Threat', @strategy_category_name = 'Social';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Population growth', @strategy_type_name = 'Threat', @strategy_category_name = 'Social';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'More congestion', @strategy_type_name = 'Threat', @strategy_category_name = 'Social';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Little media usage', @strategy_type_name = 'Threat', @strategy_category_name = 'Social';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'No one knows who LivableStreets is', @strategy_type_name = 'Threat', @strategy_category_name = 'Social';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Attend more public meetings', @strategy_type_name = 'Threat', @strategy_category_name = 'Social';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Not good at attracting drivers', @strategy_type_name = 'Threat', @strategy_category_name = 'Social';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Need to proactively empower other communities', @strategy_type_name = 'Threat', @strategy_category_name = 'Social';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Stratification of modes of transport with infighting', @strategy_type_name = 'Threat', @strategy_category_name = 'Social';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Cars still the priority mode of transportation', @strategy_type_name = 'Threat', @strategy_category_name = 'Technological';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Not leveraging best practices of other organizations', @strategy_type_name = 'Threat', @strategy_category_name = 'Technological';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Could utilize technology as an organization better', @strategy_type_name = 'Threat', @strategy_category_name = 'Technological';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Cannot rely on technology to solve problems', @strategy_type_name = 'Threat', @strategy_category_name = 'Technological';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Systems and technologies complicate rather than simplify', @strategy_type_name = 'Threat', @strategy_category_name = 'Technological';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Lots of infrastructure to maintain and understand', @strategy_type_name = 'Threat', @strategy_category_name = 'Technological';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Big money being diverted to technology solutions', @strategy_type_name = 'Threat', @strategy_category_name = 'Technological';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Tools being used to plan -- ex: traffic -- widely criticized and not matching updated guidebooks', @strategy_type_name = 'Threat', @strategy_category_name = 'Technological';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Strong reputation in community', @strategy_type_name = 'Strength', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Respected as thought leaders', @strategy_type_name = 'Strength', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Brand identity', @strategy_type_name = 'Strength', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Access to government at high levels', @strategy_type_name = 'Strength', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Ability to balance influence and advocacy', @strategy_type_name = 'Strength', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Consensus building', @strategy_type_name = 'Strength', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Network of related organizations and volunteers', @strategy_type_name = 'Strength', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Strong outreach capacity to current audiences', @strategy_type_name = 'Strength', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Connections and collaborations', @strategy_type_name = 'Strength', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Dedicated network of volunteers', @strategy_type_name = 'Strength', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = '4 effective full-time employees', @strategy_type_name = 'Strength', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Ability to motivate and inspire', @strategy_type_name = 'Strength', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Engaged Board of Directors', @strategy_type_name = 'Strength', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'High-capacity, technically capable committees', @strategy_type_name = 'Strength', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Strong growth trajectory', @strategy_type_name = 'Strength', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Diverse skillsets, age, and gender', @strategy_type_name = 'Strength', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Self-Critical', @strategy_type_name = 'Strength', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Planning and visibility', @strategy_type_name = 'Strength', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Multi-modal', @strategy_type_name = 'Strength', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Accessible to some newcomers and community', @strategy_type_name = 'Strength', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Proven track record of successes', @strategy_type_name = 'Strength', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Diverse funding sources', @strategy_type_name = 'Strength', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Use of development technology', @strategy_type_name = 'Strength', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Media plan, relationships with media', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Relationships with business leaders', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Impact on non-Cambridge neighborhoods', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Sharing our stories and successes', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Social Media', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Coordinated Communications Plan', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Leadership development in volunteers / Board', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Lack of HR / Admin staff', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Need more support staff', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Top-heavy', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Staff / Volunteer growth plan', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'No Finance Committee', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Dependent on a few individuals', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'No Vice Chairs of committees', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Day-to-Day Roles and Responsibilities', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Saying no to many good initiatives', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Addressing external changes / rapid response', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Lack of fundraising experience on Board + Staff', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Unclear value proposition to members', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Untapped funding potential', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Diversity in race, ethnicity, socioeconomic', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Young, predominately white image', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Diversity within the organization', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Non-development technology', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';
EXEC dbo.uspAddSWOTStrategy @strategy_name = 'Evaluation and Measurement', @strategy_type_name = 'Weakness', @strategy_category_name = 'Unknown';