INSERT INTO [lookup].[SWOT_Strategy_Type] (Strategy_Type_Name, Strategy_Category_Name)
VALUES	  ('Strength', 'SWOT')
		, ('Weakness', 'SWOT')
		, ('Opportunity', 'SWOT')
		, ('Threat', 'SWOT')
		, ('Strength Opportunity Intersection', 'SWOT Analysis')
		, ('Strength Threat Intersection', 'SWOT Analysis')
		, ('Weakness Opportunity Intersection', 'SWOT Analysis')
		, ('Weakness Threat Intersection', 'SWOT Analysis')